# cmake/ParseGameToml.cmake
function(parse_game_toml TOML_PATH)
    if(NOT EXISTS "${TOML_PATH}")
        message(FATAL_ERROR "[ParseGameToml] File not found: ${TOML_PATH}")
    endif()

    file(STRINGS "${TOML_PATH}" TOML_LINES)

    set(in_game FALSE)
    set(v_name "")
    set(v_jar "")
    set(v_main "")
    set(v_outdir "game_src")

    foreach(line IN LISTS TOML_LINES)
        string(REGEX REPLACE "#.*$" "" line "${line}")
        string(STRIP "${line}" line)
        if("${line}" STREQUAL "")
            continue()
        endif()

        if("${line}" MATCHES "^\\[game\\]$")
            set(in_game TRUE)
            continue()
        endif()
        if("${line}" MATCHES "^\\[[a-zA-Z]")
            set(in_game FALSE)
            continue()
        endif()

        if(in_game)
            if("${line}" MATCHES "^name[ \t]*=[ \t]*\"([^\"]*)\"")
                set(v_name "${CMAKE_MATCH_1}")
            endif()
            if("${line}" MATCHES "^jar[ \t]*=[ \t]*\"([^\"]*)\"")
                set(v_jar "${CMAKE_MATCH_1}")
            endif()
            if("${line}" MATCHES "^main_class[ \t]*=[ \t]*\"([^\"]*)\"")
                set(v_main "${CMAKE_MATCH_1}")
            endif()
            if("${line}" MATCHES "^output_dir[ \t]*=[ \t]*\"([^\"]*)\"")
                set(v_outdir "${CMAKE_MATCH_1}")
            endif()
        endif()
    endforeach()

    if("${v_name}" STREQUAL "")
        message(FATAL_ERROR "[ParseGameToml] 'name' not found in ${TOML_PATH}")
    endif()
    if("${v_jar}" STREQUAL "")
        message(FATAL_ERROR "[ParseGameToml] 'jar' not found in ${TOML_PATH}")
    endif()
    if("${v_main}" STREQUAL "")
        message(FATAL_ERROR "[ParseGameToml] 'main_class' not found in ${TOML_PATH}")
    endif()

    get_filename_component(toml_dir "${TOML_PATH}" DIRECTORY)
    if(NOT IS_ABSOLUTE "${v_jar}")
        set(v_jar "${toml_dir}/${v_jar}")
    endif()

    set(GAME_NAME       "${v_name}"   PARENT_SCOPE)
    set(GAME_JAR        "${v_jar}"    PARENT_SCOPE)
    set(GAME_MAIN_CLASS "${v_main}"   PARENT_SCOPE)
    set(GAME_OUTPUT_DIR "${v_outdir}" PARENT_SCOPE)

    message(STATUS "[J2MERecomp] game=${v_name}  jar=${v_jar}  main=${v_main}")
endfunction()
